# Generated by Django 2.2.4 on 2019-08-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='slub',
            new_name='slug',
        ),
    ]
